### ISSUE TITLE
Capital i vs. lowercase l

### ISSUE THREAD

**Issue by RGB-es** [CatharsisFonts/Ysabeau#2]
I know that the capital i is shorter than the lowercase l, but sometimes that difference is not enough:

![eau-i-vs-l](https://cloud.githubusercontent.com/assets/7756783/23057951/cd630ce8-f4f2-11e6-948f-6565d9db0199.png)

Is it possible to make the lowercase l a bit different? Perhaps with a small hook, like on the italic version?

![eau](https://cloud.githubusercontent.com/assets/7756783/23057973/f01019de-f4f2-11e6-94d8-eb8bf214ec19.png)

Many thanks for your work! 

[side note: I'm testing Eau De Garamond on a document together with Cormorant Garamond (for headings) and EBGaramond (for body text) and it is great! Now I need to find a suitable monospaced font ;) ]

**Comment by CatharsisFonts** [comment]
Dear RGB-es,

I do have a tailed ell implemented in the Infant fonts (or SS01 in the default fonts):
<img width="601" alt="screen shot 2017-02-17 at 11 21 04" src="https://cloud.githubusercontent.com/assets/13754106/23062078/adb1c292-f504-11e6-9b6f-2bfb9a390f53.png">
I'd rather not make it the default ell for the typeface, since Garamond's ell is flat-footed.
