### ISSUE TITLE
Uppercase W 

### ISSUE THREAD

**Issue by Nivirce** [CatharsisFonts/Ysabeau#5]
I'll start by saying this is probably just down to personal preference, but let's have a look at the uppercase W of your previous font, Commorant (that seems to me as pretty much a companion to this one):
![clipboard02](https://user-images.githubusercontent.com/44560742/49702034-1eec1c80-fbdb-11e8-939b-44f6aaeacbcf.png)
Now let's have a look at EauDeGaramond's uppercase W:
![clipboard03](https://user-images.githubusercontent.com/44560742/49702062-7ab6a580-fbdb-11e8-93c0-b7951b8080c4.png)
Aside from one being a serif font and the other being sans-serif, what's the big difference? The first has four upper-terminals while the second has three. More than that, while on the first the lines meet a little before their end, in the second they meet right at the end-point.

And why is it a problem?

Well, as I said, it's mostly down to personal preference, but 3 upper-terminals that meet right at the end-point is a bit... bland. Every sans-serif font does it. Arial does it, Calibri does it, Franklin Gothic does it, even Roboto does it. It's bland. Not only that, but I feel like it does not go well with the 4 terminals of Commorant.

Compare with something like Scala Sans:
![clipboard04](https://user-images.githubusercontent.com/44560742/49702319-0fba9e00-fbde-11e8-8247-cb7e0290c8d2.png)
Four upper-terminals in sans-serif makes the font a bit more unique, but it's also not so uncommon that it seems more like the designer is just trying to bring attention to themselves.

Of course, a similar effect can be achieved by just moving the meeting point between the two central lines of the central upper-terminal little below their current position, cutting one of them short, but I believe 4 upper-terminals would be a more elegant solution.

**Comment by CatharsisFonts** [comment]
Hi, 

the four-pronged /W design works in a high-contrast and/or low-weight setting, but even there, it looks quite antiquated and clumsy. I don't think it would work well for Eau. I'm willing to depart from the Garamond tradition here for the sake of making the low-contrast style work, especially in the heaviest weights.

Cheers, Christian

**Comment by vpetzel** [comment]
Hi Christian,

I’ve done a small mockup example of how such a /W could look in Ysabeau. As one can see, this design is basically unusable in anything starting at regular weight, but it’s quite appealing in lower weights. It definitely doesn’t fit Ysabeau as standard glyph, but I guess it might actually look less blunt than the default shape in some cases of larger font sizes, e.g. big headers &c.
Maybe you could consider to add such a design as an opentype alternate feature to the lighter fonts?

Valentin

[test.pdf](https://github.com/CatharsisFonts/EauDeGaramond/files/3070696/test.pdf)

**Comment by CatharsisFonts** [comment]
I'll consider it, but I don't particularly like the looks of it in the mock-up. It won't be high on the to-do list; drawing the Heavy masters will keep me busy for the foreseeable future.
Cheers, Christian

**Comment by vpetzel** [comment]
Me neighter. Though I did not put much effort into refining this, I’m pretty sure it would just look off in most cases, but as I said, it might work well in light weights at very large font sizes, depending on the style you want to achieve. I think it wouldn’t work at all in capitals, but see this example in 86pt:
[testbig.pdf](https://github.com/CatharsisFonts/EauDeGaramond/files/3077290/testbig.pdf)
The upper text looks fine, but imo the /W looks just a bit off, I think that’s because it’s quite devoid of characteristic points in the middle range while have quite a few end points and angles at the top and the bottom.
I think the lower text looks quite acceptable, and the /W feels slightly more harmonic with the minuscles next to it, but then, it breaks style with /w a bit ...

Anyway, depending on what you want it might be a good thing.

BTW: Thank you for this beautiful typeface. It’s really become one of my absolute favorite sans serif fonts.

Valentin

**Comment by cmahte** [comment]
I don't know enough about the Glyphs program so this suggestion might not be feasible, but the lighter weights are a bit out of balance: too much white. Instead of 2 minor strokes in the middle, possibly only 1  but not intersect at the top?  

![W](https://user-images.githubusercontent.com/11809394/56093944-27f43f80-5e94-11e9-8d7e-9b7dc5e55ed9.png)

(and this is a garamond serif type, but shows the overlay of the strokes.) 

This allows the light weights to keep a normal contrast, but also the heavy strokes can just grow the stroke on one side so that the heavy weights don't even have the minor stroke. It additionally allows the width of the W to be less of a contrast and distraction, when viewing the whole page. 

The minor stroke can be very minimal and produce the unifying effect.  It won't take much to make it a 'single' W from far away instead of a 'stop: is that W or 2 Vs.'  

I also think the typeface is beautiful and fills a much needed gap in low x sans. Thank you!

**Comment by vpetzel** [comment]
Hi Michael,

I think this would a bit weird in a low contrast sans serif setting. It would probably look somewhat like this in Ysabeau:
[w.pdf](https://github.com/CatharsisFonts/EauDeGaramond/files/3077729/w.pdf)

I’d say the /W in Ysabeau looks good up to maybe Light, due to having that bit of contrast making it feel organic. In the lighter weights it just looks like a very big geometric zigzag line.
Maybe just lowering the intersecting point in light weights would do the trick? Like this:
[w2.pdf](https://github.com/CatharsisFonts/EauDeGaramond/files/3077757/w2.pdf)

Valentin
